#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 24 10:12:01 2019

@author: rmoctezuma
"""

import h5py
import keras
import numpy as np

arr = np.random.randn(1000)

with h5py.File('TRAAAAW128F429D538.h5', 'w') as f:
    dset = f.create_dataset("default", data=arr)
    
with h5py.File('TRAAAAW128F429D538.h5', 'r') as f:
    data = f['default']
    print(min(data))
    print(max(data))
    print(data[:15])
